# Generated by Django 4.1.7 on 2023-03-19 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Contato', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contato',
            options={'ordering': ['nome'], 'verbose_name': 'Contato', 'verbose_name_plural': 'Contatos'},
        ),
    ]
