# Generated by Django 4.1.7 on 2023-03-18 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='data_de_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
