# Generated by Django 4.1.7 on 2023-03-25 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_user_nome_user_sobrenome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nome',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='sobrenome',
            field=models.CharField(max_length=50),
        ),
    ]
