# Generated by Django 4.1.7 on 2023-03-25 20:02
from datetime import timezone

from django.db import migrations

def add_User(apps, schema_editor):
    User = apps.get_model('User', 'User')
    User.objects.create(nome='admin', sobrenome='admin', username='admin',  email='admin@admin.com', cpf='12345678901', telefone='12345678901', endereco='admin', cidade='admin', estado='admin', cep='12345678', password='admin', is_staff=True, is_superuser=True, is_active=True, date_joined=timezone.now(), last_login=timezone.now(), data_de_nascimento=timezone.now())

class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_alter_user_nome_alter_user_sobrenome'),
    ]

    operations = [
        migrations.RunPython(add_User, reverse_code=migrations.RunPython.noop),
    ]
